In [1]:
import numpy as np

In [2]:
nums = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [3]:
nums

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
np.sum(nums, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [9]:
np.sum(nums, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [10]:
np.sum(nums, axis=2)

array([[ 6, 15],
       [24, 33]])

In [12]:
nums.shape

(2, 2, 3)

In [16]:
nums = np.array([[1,2,3],[4,5,6]])

nums

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.sum(nums, axis=0)

array([5, 7, 9])

In [15]:
np.sum(nums, axis=1)

array([ 6, 15])