In [32]:
import numpy as np

In [33]:
nums2 = np.array([1,2])
nums2x2 = np.array([[1,2],[3,4]])
nums2x2x2 = np.array([[[1,2],
                       [3,4]],[[5,6],
                               [7,8]]])

In [48]:
####### One Dimensional

# [ (0), (1) ]

####### Two Dimensional

# [ (0, 0), (0, 1) ]
# [ (1, 0), (1, 1) ]

####### Three Dimensional

# [ (0, 0, 0), (0, 0, 1) ]
# [ (0, 1, 0), (0, 1, 1) ]

#                        [ (1, 0, 0), (1, 0, 1) ]
#                        [ (1, 1, 0), (1, 1, 1) ]


print(nums2x2x2[0,0,0]) # 1
print(nums2x2x2[1,1,1]) # 8

print(nums2x2x2[0,1,0]) # 3
print(nums2x2x2[1,0,1]) # 6

1
8
3
6


In [34]:
# axis 0 -
#      [1,2]

np.sum(nums2, axis=0) # eliminate axis 0

3

In [44]:
# axis   1 -
#      0 [1,2]
#      | [3,4]

print(np.sum(nums2x2, axis=0)) # eliminate axis 0
print(np.sum(nums2x2, axis=1)) # eliminate axis 1

print(nums2x2[:, 0]) # [1 3], both values on axis 0

print(nums2x2[0, :]) # [1 2], both values on axis 1

[4 6]
[3 7]
[1 3]
[1 2]


In [42]:
# axis  0 2 -
#       1 \ 
#       |  [1,2] 
#          [3,4] 
#              [5,6]
#              [7,8]


print(np.sum(nums2x2x2, axis=0)) # eliminate axis 0
print(np.sum(nums2x2x2, axis=1)) # eliminate axis 1
print(np.sum(nums2x2x2, axis=2)) # eliminate axis 2

print(nums2x2x2[:, 0, 0]) # [1 5], both values on axis 0
print(nums2x2x2[:, 1, 1]) # [4 8], both values on axis 0

print(nums2x2x2[0, :, 0]) # [1 3], both values on axis 1
print(nums2x2x2[1, :, 1]) # [6 8], both values on axis 1

print(nums2x2x2[0, 0, :]) # [1 2], both values on axis 2
print(nums2x2x2[1, 1, :]) # [7 8], both values on axis 2



[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]
[1 5]
[4 8]
[5 7]
[6 8]
[1 2]
[7 8]
